import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import { toast, ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';
import { IndiaStatsCard } from "../components/IndiaStatsCard";
import { Loading } from "../components/Loading";
import SideNav from "../components/SideNav";
import { WorldStatsCard } from "../components/WorldStatsCard";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const [data, setdata]: any = useState([]);
  const [statedata, setStatedata]: any = useState([]);
  const [view, setview]: any = useState(true);

  const getWorldData = async () => {
    try {
      const resw = await fetch("https://covid-19.dataflowkit.com/v1");
      const worlddata = await resw.json();
      const res = await fetch("https://api.rootnet.in/covid19-in/stats/latest");
      const statewiseData = await res.json();
      setStatedata(statewiseData.data["regional"]);
      setdata(worlddata[0]);
      setview(false);
      // console.log(data["Total Cases_text"]);
    } catch (error) {
      setview(false);
      console.log(error);
    }
  };
  const notify = () => toast.success('Give me a ⭐ on GitHub.', {
    position: "top-right",
    autoClose: 3000,
    theme:'dark',
    hideProgressBar: false,
    closeOnClick: true,
    pauseOnHover: true,
    draggable: true,
    progress: undefined,
    style:{
      backgroundColor:'#404a63'
    }
    });

   
  useEffect(() => {
    getWorldData(); notify();
  }, []);
  return (
    <>
      <Head>
        <title>Covid 19</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <ToastContainer
        position="top-right"
        autoClose={5000}
        hideProgressBar={false}
        newestOnTop={false}
        closeOnClick
        rtl={false}
        pauseOnFocusLoss
        draggable
        pauseOnHover
      />
        <div className='dark flex flex-row h-screen w-screen font-Roboto  '>
          <div className=' h-full md:w-[7%] w-[20%]'>
            <SideNav />
          </div>
          <div className=' h-full md:w-[93%] w-[80%] bg-[#1a2235] overflow-scroll overflow-x-hidden'>
            <div className='ml-4 mt-4 text-3xl text-[#a6aec4] font-semibold'>
              Dashboard
            </div>
            <div className='ml-4 mt-2 text-md text-[#768098]'>
              Last Updated on {data["Last Update"]}
            </div>
            <div className='flex flex-row flex-wrap'>
              <WorldStatsCard
                caseType='Confirmed Cases'
                textcolor='text-red-400'
                message='Total Confirmed covid-19 cases across the world.'
                cases={data["Total Cases_text"]}
              />
              <WorldStatsCard
                caseType='Active Cases'
                textcolor='text-blue-400'
                message='Total active covid-19 cases across the world.'
                cases={data["Active Cases_text"]}
              />
              <WorldStatsCard
                caseType='Recovered'
                textcolor='text-green-400'
                message='Total Recovered covid-19 patients across the world.'
                cases={data["Total Recovered_text"]}
              />
              <WorldStatsCard
                caseType='Deceased'
                textcolor='text-gray-400'
                message="Total Death's of covid-19 patients across the world."
                cases={data["Total Deaths_text"]}
              />
            </div>
            <div className='ml-4 mt-4 text-3xl text-[#a6aec4] font-semibold'>
              India
            </div>
            <div className='ml-4 mt-2 text-md text-[#768098]'>
              Last Updated on {data["Last Update"]}
            </div>
            <div className='flex flex-row flex-wrap'>
              {statedata.map((data: any, i: number) => {
                if (i != 0 && i != 7) {
                  return (
                    <IndiaStatsCard
                      key={i}
                      State={data.loc}
                      confirmed={data.totalConfirmed}
                      recovered={data.discharged}
                      deceased={data.deaths}
                    />
                  );
                }
              })}
            </div>
          </div>
        </div>
        {view&&<Loading/>}
    </>
  );
};

export default Home;
